name: Pull Request

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      mode: pr
      ref: ${{ github.sha }}
